name: Deploy to Github Pages
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: cd ./mkdocs-CTAR/; ls; pwd
      - run: cd ./mkdocs-CTAR/; mkdocs gh-deploy --force
